name: PR Triage (labels & contributing check)

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-label:
    name: Add "needs review" label
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            const label = 'needs review';
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            // Create the label if it doesn't exist
            try {
              await github.rest.issues.getLabel({ owner, repo, name: label });
            } catch {
              await github.rest.issues.createLabel({
                owner, repo, name: label, color: 'FBCA04', description: 'Awaiting maintainer review'
              });
            }

            // Add the label to the PR
            await github.rest.issues.addLabels({
              owner, repo, issue_number, labels: [label]
            });

  check-contributing:
    name: Verify "I have read CONTRIBUTING" checkbox
    runs-on: ubuntu-latest
    steps:
      - name: Enforce checkbox in PR body
        id: enforce
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = (pr.body || '').toLowerCase();

            // Look for a checked box referencing CONTRIBUTING
            // e.g. "- [x] I have read the CONTRIBUTING.md"
            const ok =
              /\[[xX]\]/.test(body) &&
              /(contributing\.md|contributing guidelines|contributing)/i.test(pr.body || '');

            if (!ok) {
              // (Optional) post a helpful comment once per PR head SHA
              const { owner, repo } = context.repo;
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body: [
                  "👋 Thanks for the PR! To keep things consistent, please acknowledge you've read the contributing guidelines.",
                  "",
                  "Add this to your PR description (and check the box):",
                  "",
                  "- [x] I have read the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) and followed the guidelines."
                ].join("\n")
              });
              core.setFailed("Contributor guidelines checkbox not found in PR description.");
            } else {
              core.info("Contributor guidelines checkbox present. ✅");
            }
